dp-api-router.nomad
The nomad plan contains the wrong task name. This should be dp-api-router
=> Fixed an error in the nomad plan

README.md, config/config.go, config/config_test.go, interceptor/interceptor.go, interceptor/interceptor_test.go, main.go
- Add interceptor middleware to prepend any urls with environment host
- Set the environment variable `export ENV_HOST=https://beta.ons.gov.uk"`
- Request a valid version through the api router:
`curl -v http://localhost:23200/v1/datasets/{id}/editions/{edition}/versions/{version} | jq`
- Verify that the links, dimensions and download hrefs all contain the environment domain with either api. / download. correctly prefixed.
Team B
=> Add interceptor middleware to prepend any urls with environment host

main.go, vendor/github.com/gorilla/handlers/LICENSE, vendor/github.com/gorilla/handlers/README.md, vendor/github.com/gorilla/handlers/canonical.go, vendor/github.com/gorilla/handlers/compress.go, vendor/github.com/gorilla/handlers/cors.go, vendor/github.com/gorilla/handlers/doc.go, vendor/github.com/gorilla/handlers/handlers.go, vendor/github.com/gorilla/handlers/handlers_go18.go, vendor/github.com/gorilla/handlers/handlers_pre18.go, vendor/github.com/gorilla/handlers/proxy_headers.go, vendor/github.com/gorilla/handlers/recovery.go, vendor/vendor.json
Added CORS handler to allow cross-origin GET and POST requests in web.
Run with EnablePrivateEndpoints=false and turn on another api (I used dataset) then confirm via curl with:
curl -H "Origin: literallyanywhere.com" \
-H "Access-Control-Request-Method: GET" \
-X OPTIONS --verbose http://localhost:23200/v1/datasets
An Access-Control-Request-Method of GET or POST should return 200, all other methods should return 405.
Note: This is simulating a pre-flight request. GET, POST and HEAD are "simple" requests and only trigger preflight when they include non CORS-safelisted request headers: 
https://fetch.spec.whatwg.org/#cors-safelisted-request-header
We could force preflights for all requests, but this is part of how CORS works so seems OTT for now.
Anyone.
=> Enabled CORS for GET in web

interceptor/interceptor.go, interceptor/interceptor_test.go, main.go, proxy/proxy.go
Update interceptor to implement `http.RoundTripper` instead of writer, to allow the response body to be correctly post processed. (Before the Write method was being written to in chunks so sometimes not all of the bytes were valid json)
Run unit tests and verify the logic is correct
Anyone
=> Switch the interceptor to use transport instead of writer

config/config.go, config/config_test.go, main.go
Added a feature flag so we can choose between enabling routes to everything or just the legacy/existing website apis (so we can deploy this in advance of the rest of cmd).
Note - **DO NOT DEPLOY** until all the secrets are updated and apps redeployed as v1 endpoints are disabled by default.
Sanity check
Anyone
=> added feature flag for enable/disable cmd routes

config/config.go, config/config_test.go, middleware/origin.go
The cross origin handler was too strict, and was automatically failing all non cross origin requests (as they'll never have an origin to check). Have modified it to apply more selectively.
Also added the other .publishing domains to save us a little work in future.
Sanity check
anyone
=> updated origin handler and default allowed origins

dp-api-router.nomad
The secrets have now been split into web and publishing.  The secrets
are determined by the task name.  This change ensures the correct
secrets are loaded.
=> Ensure correct secrets path is used

middleware/audit.go, middleware/audit_test.go
- Added `clickEventLog ` to audit ignored paths list
- fixed comment in test
- Make sure change make sense (according to https://github.com/ONSdigital/florence/pull/450 PR comment)
- Unit tests should pass
Anyone
=> Ignore clickEventLog in audit middleware

interceptor/interceptor.go
In some calls, a nil type is provided to the RoundTripper. This was not correctly handled before and it was generating a panic. Then the caller wouldn't receive a valid response for the call that was being routed.
I added a nil pointer check, and if the type is nil we return an error, which is a valid scenario (it just means that the links will not be updated in the request body).
Example of a call that was failing: 
```
curl --location --request GET 'http://<filterDatasetController>/filters/39835bee-b4eb-4aa5-a5a3-3f8e3e4f220a/dimensions' \
--header 'X-Florence-Token:<florenceToken>'
```
- Make sure code changes make sense
- Unit tests should pass
Anyone
=> Handle nil resource type in interceptor reflect

middleware/origin.go, middleware/origin_test.go
Origin middleware will allow any origin if '*' is provided in config. This is to support configs that were observed in dp-configs, although they are not used at the moment (in web mode this middleware is disabled).
- Make sure code changes make sense
- Unit tests should pass
Anyone
=> Origin middleware allows any origin if the '*' wildchar is provided

service/service.go
Create Zebedee client always (regardless of the auditing flag).
That is because we need to proxy Zebedee calls even if auditing is disabled.
- Make sure code changes make sense
- Unit tests should pass
Anyone
=> Create Zebedee client and register its checker always

middleware/origin.go, middleware/origin_test.go, service/service.go
Public API requests are currently being blocked from other domains due
to our CORS headers. This fix ensures that in public mode the CORS
allowed origin will always be set to a wildcard, meaning that all public
API requests will be allowed.
Anyone but me.
=> Fix CORS issue with public API access

middleware/beta.go, middleware/beta_test.go, service/service.go
When the beta domain restriction is enabled, it blocks all traffic that is not for the `api.beta` domain. We need to allow all internal traffic through this restriction now that all internal API requests go through the API router.
- Allow internal traffic through the beta domain restriction 
- Do not apply the beta domain restriction to zebedee (legacy) endpoints
- Review code / tests
Anyone
=> Allow internal traffic through the beta domain restriction 

middleware/audit.go, middleware/audit_test.go
Added `/hierarchies` to the skip identity check whitelist as hierarchy API is not an authenticated service.
=> added /hierarchies to ignore identity whitelist

interceptor/interceptor.go, interceptor/interceptor_test.go
When no json was being returned, for instance on some 404s, failing to unmarshal the empty string was causing noisy errors. If the body has no length, theres nothing to intercept/the function should return
Make sure tests pass and api router still behaves as normal
Make sure empty responses no longer error
Anyone
=> Fix links interceptor throwing json error on empty response

interceptor/interceptor.go
Ensure that a closed response body is not returned for empty responses
-The original response body is closed already, so returning it can cause upstream code to fail if it attempts to read the body. Instead return a new empty reader that will not error when closed.
Sanity check (I could not replicate locally)
Anyone
=> Ensure that a closed response body is not returned for empty responses

service/service.go
https://trello.com/c/RGbqzfZK/4893-make-dp-search-query-available-through-api-router-1
- Add new route /dimension-search to point to `dp-dimension-search-api` (note that `/search` is also pointing to the service which is okay for now). This will be changed in the future. 
- Check if the code changes make sense
Anyone - Justin made the changes
=> add additional new route to point to dimension-search-api

config/config.go, config/config_test.go, service/service.go, service/service_test.go
Add new config `DimensionSearchAPIURL`
Add `/dimension-search` with reference to the new config
Add tests for the particular endpoint as well
Please note that `SearchAPIURL` and `DimensionSearchAPIURL` have the same values. The `SearchAPIURL` value will be changed in the future but the duplication of these values are meant to be there
Check if the new config has been added and used correctly
Check if the new endpoint has been added correctly with comparison to how previous endpoints were added
Check if the tests pass
Anyone - Justin made the changes
=> add dimension search endpoint to api router

interceptor/interceptor.go, interceptor/interceptor_test.go
- Do not rewrite URL's that don't need it
The API router rewrites the hostname of URL's, to replace them with the API router URL. If a URL is already correct the API router would still rewrite the URL, causing it to duplicate the version. This is why some API responses have '/v1/v1' in URL's.
Review changes / tests
Anyone
=> Do not rewrite URL's that don't need it

dp-api-router.nomad
Revert the transitional job name as the deployer assumes the job always matches the app name.
Anyone but me.
=> Revert transitional nomad job name

README.md, config/config.go, config/config_test.go
- Update SEARCH_API_URL to point to new `dp-search-api` (previously known as `dp-search-query`)
- Please note that the secret of dp-api-router will be updated for this change and this is in the PR (https://github.com/ONSdigital/dp-configs/pull/266)
- Check if the code changes make sense
- Check if the tests pass
Anyone
=> update search-api URL to point new search-api

interceptor/interceptor.go, interceptor/interceptor_test.go, middleware/audit.go, middleware/audit_test.go, middleware/path_filter_test.go, service/service.go, service/service_test.go
Fix linter suggested Issues that can be fixed.
1. Check err return from io.Copy and w.Write
2. Improve regexp
3. Close response Body in tests
4. remove unused variables & adjust comments.
5. Remove not needed log.Event() that is adding to HEAP for every Identity check.
6. Remove unused 'errDo'
Visual check, run tests
anyone, but Nathan ideally
=> Fix linter suggested Issues.

interceptor/interceptor.go, interceptor/interceptor_test.go
Exclude the the dp-identity-api requests from the body update process to debug where the responses are failing.
Read through the changes
Anyone but me
=> add update body ignore for debugging nginx failure location

event/producer_test.go, interceptor/interceptor.go, interceptor/interceptor_test.go, main.go, proxy/proxy.go, service/service_test.go
As per title
Visual inspection.
Run tests ... with debugger, single stepping (add breakpoints) to observe that only files starting with { or [ are unmarshaled.
Anyone.
=> Only unmarshal json and map, code clean up, restrict log length of body

service/service_test.go
Tidy the testing of the observation feature flag.
Rather than setting it to true for all the test cases with an outer convey (and having a partial reduced separate convey for when it's false), create specific cases testing the relevant scenarios (datasets).
Sense check and test pass
Anyone
=> Tidy usage of feature flag in test

config/config.go, config/config_test.go, service/service.go, service/service_test.go
Added endpoint routing and configuration for population-types API
Added a test seam allowing reset of configuration to `nil` so that unit tests can verify environment variable binding (Config.go: `Flush()`)
Read. Evaluate.
Gophers
=> Add population-types resource endpoint to api router

README.md, config/config.go, config/config_test.go, service/service.go, service/service_test.go
Adding an `/interactives` route, pointing to a new API (coming soon) for managing interactives (e.g. the iframe here: https://www.ons.gov.uk/businessindustryandtrade/internationaltrade/articles/internationalimportsofservicestosubnationalareasoftheuk/2017#service-imports-into-the-english-regions-and-three-devolved-nations).
Notes:
Behind a feature toggle: off by default
Its v basic - check code & tests pass enough I think
Anyone
=> Add route for /interactives - feature toggle protected

README.md, config/config.go, config/config_test.go, service/service.go, service/service_test.go
add dp-geodata-api (private, versioned) to /geodata route
- Add private versioned proxy from /geodata to cfg.GeodataAPIURL
- Add tests for proxying to service_test.go
- Add config tests to config_test.go
Run tests
run both dp-api-router and dp-geodata-api locally and check requests to localhost:23200/v1/geodata/metadata (e.g.) are proxied properly
Anyone
=> add dp-geodata-api (private, versioned) to /geodata route

config/config.go, config/config_test.go, service/service.go, service/service_test.go
Move dp-geodata-api proxy from private APIs to public ones +
refactor tests. This change needed as the API must be accessible
to the web VPC.
Run tests, read the code
Anyone
=> move geodata api from private to public

.nancy-ignore, service/service.go, service/service_test.go
See title
Check `/navigation` endpoint routes requests to topics API
Anyone
=> Extend api router to route /navigation requests to topics API

.nancy-ignore, Makefile, README.md, config/config.go, config/config_test.go, event/mock/marshaller.go, middleware/mock/router.go, proxy/mock/reverse_proxy.go, service/mock/healthcheck.go, service/mock/initialiser.go, service/service.go, service/service_test.go
- Ensure Downloads and Files endpoint available in Web and Publishing by @braddle in https://github.com/ONSdigital/dp-api-router/pull/155
- Add /areas endpoint to go to areas-api (and not dimensionsAPI) by @gedge in https://github.com/ONSdigital/dp-api-router/pull/158
- Test to use api router port by @rafahop in https://github.com/ONSdigital/dp-api-router/pull/160
- Add search-reindex-api endpoints for publishing @justinpjose in https://github.com/ONSdigital/dp-api-router/pull/161
**Release PR: https://github.com/ONSdigital/dp-api-router/pull/162**
- Check if the changes make sense
- Check if the test passes
- Anyone
=> Release 1.23.0

service/service_test.go
Test the case when the `metadata extractor api flag is disabled and private endpoints flag is enabled`.
Run tests
Anyone
=> Add missing test for /cantabular-metadata route

README.md, config/config.go, config/config_test.go, service/service.go, service/service_test.go
This feature flag is no longer required and can be safely removed.
Make sure the code behaves in the same way as when the flag is true.
Anyone
=> Remove ENABLE_TOPIC_API flag

config/config.go, config/config_test.go, service/service.go, service/service_test.go
Added routing for `/datasets/{id}/editions/{edition}/versions/{version}/json` endpoint which sits on `dp-cantabular-filter-flex-api`
Anyone
=> add routing for dataset-json endpoint

README.md, config/config.go, config/config_test.go, service/service.go, service/service_test.go
The Articles API has been removed and the readme updated to reflect this. The Articles API was created to replace existing functionality in babbage but is now being "moth-balled" because it's taken a low priority. The following ticket contains this task:
https://trello.com/c/rzIQoHXj/1383-make-articles-api-read-only
Check that this service no longer routes to the Articles API, that the readme looks correct, and that the tests pass.
Anyone but me
=> Remove articles api

service/service.go, service/service_test.go
Adding path for census-observations to redirect to cantabular filter flex api.
Ensure the tests pass and the changes make sense.
Anyone.
=> Adding path for census-observations-endpoint

README.md, config/config.go, config/config_test.go, service/service.go
Added feature flagged search scrubber api routing.
The feature flag is more generic as I think it should switch on/off all 3 nlp apis when we get there. 
Check tests pass.
Check it routes traffic to the search scrubber api when turned on. 
Not me.
=> Add search scrubber api

service/service.go
Re-add the interceptor to filter-flex routes (it turns out it does still need to be translated to change the URLS)
NB…
- This reverts the change for these routes from #211 
- The `/custom/filters` route (on line 167) was never intercepted before the refactoring so this still isn't intercepted, hence why it still uses non-intercepting proxy
Ensure code makes sense and tests pass
Anyone
=> Re-add interceptor to filter-flex routes

.golangci.yml, interceptor/interceptor.go
Add temporary debugging code to dump http headers on specific requests
This will enable us to add a url parameter on specific requests and get a dump of the request's internal http request headers in the logs. For safety reasons, only the values of configured headers will be dumped out in order to prevent logging of sensitive values, eg. auth tokens. Also this functionality is only enabled when the debug key is set so causes no performance hit if unintentionally deployed to prod. 
This code is only intended to be deployed as far as staging so it can be tested with CloudFlare. 
To use, the env vars will be configured in vault…
- `ROUTER_DEBUG_KEY` = some value only know to us to stop anyone public using it (debugging disabled if blank)
- `ROUTER_DEBUG_HEADERS` = comma-separated list of …
=> Add temporary debugging code to dump http headers on specific requests

README.md, config/config.go, service/initialise.go
To stop my dev-env from melting, I'm running only one kafka broker.
This causes the kafka lib to complain - it needs a min of 2 healthy brokers for producers -
and the app never gets healthy.
So, this is a env var to allow us to change that minimum healthy brokers to 1.
Only to be used in dev-env.
Use with or without `KAFKA_MIN_HEALTHY_BROKERS`
!me
=> add a for-development flag: stops error when only 1 broker in dev (producers only)

go.mod, go.sum, service/service.go
Make topic requests go through the interceptor to ensure that domains in links are replaced with the current domain instead of localhost.
https://trello.com/c/x9xXc6Ez/2060-dp-topic-api-returns-localhost-addresses
Run the application using the sandbox mongodb, then visit http://localhost:23200/v1/topics and in the data returned the links should api. appended to the front of it.
Anyone.
=> make topic requests go through the interceptor

middleware/beta.go, middleware/beta_test.go, proxy/proxy.go
Use the `version` config from the proxy instead of manually typing `/v1`
check changes are ok
ci passes
Anyone
=> use version config instead of /v1

README.md, config/config.go, config/config_test.go, service/service.go
Removed code for Sessions API as now defunct: https://github.com/ONSdigital/dp-sessions-api
Check looks ok, removed only unnecessary code. 
Not me.
=> Remove sessions API

Dockerfile.concourse
Upgrading Dockerfile.concourse to use Ubuntu-22 as requested by the platform team.
Check updated image name with whats in CI elastic container registry.
Anyone.
=> Upgrading Dockerfile.concourse to Ubuntu-22
