ONSdigital/dp-api-router

main.go
The instance endpoint should be hidden.
=> Hide instance endpoint from public view

main.go
Add version before path on resource links
=> Add version before path

interceptor/interceptor.go
Add a flusher before updating/rewriting response
=> Add flusher before writing new content

interceptor/interceptor.go
- Rewrite original response body if update fails
Test on cmd-dev env when merged
Anyone
=> Return original response body if update fails

interceptor/interceptor.go, interceptor/interceptor_test.go
- Update code to supported nested dimension hrefs
- Update code to support query parameters in hrefs correctly
Verify logic is correct
Anyone
=> Update nested dimensions href

interceptor/interceptor.go
Resource will either be map or slice, once the type is determined assert
the type onto a new variable (similar to casting) and then handle hrefs
in resource by calling checkMap. This way the router will only ever
unmarshal the byte array once.
One can use ab tool to benchmark the same requests in both branches.
=> Use reflection to determine resource type

interceptor/interceptor.go, interceptor/interceptor_test.go, vendor/github.com/ONSdigital/go-ns/LICENSE.md, vendor/github.com/ONSdigital/go-ns/common/client.go, vendor/github.com/ONSdigital/go-ns/common/errors.go, vendor/github.com/ONSdigital/go-ns/common/identity.go, vendor/github.com/ONSdigital/go-ns/common/models.go, vendor/github.com/ONSdigital/go-ns/common/rchttp.go, vendor/github.com/ONSdigital/go-ns/handlers/requestID/handler.go, vendor/github.com/ONSdigital/go-ns/log/log.go, vendor/vendor.json
What
Updated interceptor to unmarshal array response bodies.
How to review
Check code, try it.
Who can review
anyone
=> Interceptor, unmarshal array response

interceptor/interceptor.go, interceptor/interceptor_test.go, vendor/github.com/ONSdigital/go-ns/LICENSE.md, vendor/github.com/ONSdigital/go-ns/common/client.go, vendor/github.com/ONSdigital/go-ns/common/errors.go, vendor/github.com/ONSdigital/go-ns/common/identity.go, vendor/github.com/ONSdigital/go-ns/common/models.go, vendor/github.com/ONSdigital/go-ns/common/rchttp.go, vendor/github.com/ONSdigital/go-ns/handlers/requestID/handler.go, vendor/github.com/ONSdigital/go-ns/log/log.go, vendor/vendor.json
This allows links against objects within an array to be updated with the right hostname.
=> Update interceptor to marshal array of objects

dp-api-router.nomad
What
Using docker reduces the likelihood of timeout on deploy
How to review
check for typos
check repo names are consistent
check web/publishing both updated
Who can review
anyone
=> Update nomad plan to use docker instead of exec driver

README.md
=> force rebuild, trivial readme change

ci/build.yml, ci/unit.yml, go.mod
=> Upgraded to go 1.13

Makefile, ci/audit.yml, ci/scripts/audit.sh
Updated Makefile to include dependency auditing process and created audit files for CI
Check that the changes make sense, that permissions are set correctly (`chmod 755`), and that the `audit` command works as expected
Anyone
=> add dependency auditing with Nancy and implement audit CI scripts

Makefile
Fix instances of `PHONY` => `.PHONY` in Makefile
=> fix phony targets

config/config.go, config/config_test.go
Set default `AllowedOrigins` value for localhost Florence
Test with Florence
Anyone
=> Set default `AllowedOrigins` value for localhost Florence

middleware/audit.go
added v1 prefix to test theory **Hack hack hack** .... _sigh_
=> added v1 prefix to test theory **Hack hack hack**

README.md, config/config.go, config/config_test.go, service/service.go, service/service_test.go
Added upload service to config and new proxy added to the router
UploadServiceAPIURL:        "http://localhost:25100",
Check config for the url and check correct proxy has been added to the router
and check if correct tests are added
Anyone
=> Added upload-service to config

middleware/audit.go, middleware/audit_test.go
- Fixed bug query parameters encoding bug: https://trello.com/c/sDtn8pZc/4900-query-parameter-in-audit-log-is-not-utf-8-encoded.
- try to unescape special characters from RawQuery
- If it fails to unescape, use RawQuery as a fallback value
- Make sure code changes make sene
- Unit tests should pass. New tests fully cover the described functionality
Anyone
=> Audit events now unescape query parameters

config/config.go, config/config_test.go
=> Change EnableTopicAPI flag to false

Makefile
* Update to new way of running `nancy`
* Upgrade to latest `nancy` locally and check that `make audit` runs (it may still be failing)
Anyone but me.
=> Update audit to work with Nancy > 1.0.0

README.md
See title
Missing configuration variables now added to README.md
Check README.md config table covers all configuration values and the descriptions make sense and the default values match the ones on config.go
Anyone
=> Update README.md configuration table

service/service.go
Mahe API for dp-topic-api less specific
Visual inspection
anyone
=> Make API endpoint less specific

dp-api-router.nomad
Added 'system_job' tag for use in the consul templates
Check both web and publishing service definitions have 'system_job' in their tags definitions
Anyone but me
=> add 'system_job' tag to the nomad job

ci/build.yml, ci/unit.yml, config/config.go, go.mod, go.sum, interceptor/interceptor.go, proxy/proxy.go, service/service.go
- Update go version in go.mod and ci folder
- Rearrange config file structure to align with other go applications/repositories
- Pass the same context value down the service layer
- Reuse the request context when logging an event
Anyone
=> Update go version and use request context in logs

interceptor/interceptor.go
Removed the debugging statements now the bug has been resolved.
Read the changes.
Ensure all tests are passing
Anyone but me
=> remove the debugging statements now the bug has been resolved

.gitignore, Dockerfile.local, interceptor/interceptor.go, reflex
Added local dockerfile to be used for the cantabular import journey. Part of a multi-pr change.
Main PR/instructions can be found here:
https://github.com/ONSdigital/dp-compose/pull/35
Visit main PR
Anyone
=> add local dockerfile and reflex file

interceptor/interceptor.go, interceptor/interceptor_roundtrip_benchmark_test.go, interceptor/interceptor_test.go
as title
visual inspection,
run tests,
run / read comments/observations in benchmark code
anyone
=> Add extra debug, Exclude gzip, Only process stuff on 'shallUse' list, Reject non JSON things to avoid loading BIG things into HEAP memory

interceptor/interceptor.go
As per title.
Visual inspection.
Run tests.
Nathan
=> Add 3 more paths and a comment

config/config.go, config/config_test.go, service/service.go, service/service_test.go
Add versioning for release calendar
Use correct `releases` path
Check code and tests
Anyone but me
=> Add versioning for release calendar and use correct path

service/service_test.go
Group tests for population types API under a single convey to follow the same pattern in this test file
Follow BDD design (Given/When/Then)
Check the test is still valid
Anyone but maybe @goofballLogic is in the best position as he wrote the original test recently
=> Group tests for population types API

config/config.go, config/config_test.go, service/service.go, service/service_test.go
Add versioning for articles api
Refactor unit test to follow BDD
Check code and tests
Anyone
=> Add versioning for articles api

README.md
Added missing documentation in README.md
Check README.md documentation is accurate - config variable names and values
Anyone
=> Add missing IDENTITY_API config documentation to README.md

README.md, config/config.go, config/config_test.go, service/service.go, service/service_test.go
Add dp-maps-api
Review code changes to add config, reverse proxy and some minor test refactoring to simplify existing tests
Anyone
=> Add dp-maps-api

config/config.go, config/config_test.go, service/service.go
Surround new files API work in feature flag following existing practices and particularly to isolate a potential production issue 
does the api router compile
do existing routes still work
is the static files behaviour off
anyone
=> Add feature flag to static files routing to isolate potential issues

service/service.go
Add / to interim proxy to ensure /filesize does not match /files proxy
approve it
you!
=> Add / to interim proxy to ensure /filesize does not match /files proxy

Makefile, service/service.go
Making /downloads-new and /files publicly available so that they can be accessed in web environment
Ensure /downloads-new and /files can be access publicly 
Anyone
=> Ensure Downloads and Files endpoint available in Web and Publishing.

service/service_test.go
Test should use the api router port, not the api port
Tests pass
Anyone
=> Use api router port

config/config.go, config/config_test.go, service/service.go, service/service_test.go
- add dp-search-reindex-api endpoints for publishing in the api-router
- Check if the code changes make sense
- Check if the test passes
- Anyone
=> add search-reindex-api endpoints for publishing

service/service.go, service/service_test.go
Change router for area-types from `DimensionsAPI` to `PopulationTypesAPI`
Sense check it and ensure tests are :green_circle: 
Any ONS developer
=> Change router for area-types

README.md, config/config.go, config/config_test.go, service/service.go, service/service_test.go
This service is no longer being used.
Sense check it and ensure tests are :green_circle: 
Any ONS developer
=> Remove DimensionsAPI route path

middleware/audit.go
- one debug log removed
- one repeated log removed
=> remove redundant/debug logs

.golangci.yml, Makefile, event/event_test.go, event/producer_test.go, interceptor/interceptor.go, interceptor/interceptor_roundtrip_benchmark_test.go, interceptor/interceptor_test.go, main.go, middleware/audit.go, middleware/audit_test.go, middleware/beta.go, middleware/beta_test.go, middleware/origin.go, middleware/origin_test.go, middleware/path_filter.go, middleware/path_filter_test.go, proxy/proxy.go, service/service.go, service/service_test.go
This pr attempts to enable golangcilint in this repo and fix all the existing lint issues
Please check if the changes make sense and all the expected linters are enabled. 
Anyone except me
=> Enable and fix linting

middleware/audit.go, middleware/audit_test.go
See title, additional unit test to cover audit use of skip identity method
- Check changes make sense
Anyone
=> Move paths that will not be called with auth headers to skip identity

go.mod, go.sum
modified authorisation library version
Anyone but me
=> changed authorisation version

config/config.go, config/config_test.go, service/service.go, service/service_test.go
- Release 2.2.0
- Add routing for /dataset.../json endpoint
Anyone
=> add routing for dataset-json endpoint

ci/lint.yml, ci/scripts/lint.sh, middleware/audit.go
Add linter to the pipeline.
Please check if the changes make sense and all the expected linters are enabled. 
Anyone except me
=> Add linter to the pipeline

interceptor/interceptor.go, interceptor/interceptor_test.go
Add dataset_links to list of interceptor fields to replace URLs with correct domain.
Anyone
=> add interception for dataset_links doc

service/service.go, service/service_test.go
Added `/custom/filters` path to be routed to filterflex API
All test are :green_circle: 
Anyone
=> Added new path to be routed to filterflex

config/config.go, config/config_test.go, service/service.go
This adds the option to configure timeout for zebedee http request
Please check if the changes make sense
Anyone except me
=> Add zebedee client custom timeout option

config/config.go, config/config_test.go, main.go
Added batch timeout config parameter and default to fix 100% cpu issue.
Running locally CPU time is normal. Pipeline tests etc
Anyone non-AND
=> added batch timeout default 5 sec

service/service.go
Release branch containing…
- Re-add interceptor to filter-flex routes
Ensure only expected commits and tests pass
Anyone
=> Release 2.12.0

.golangci.yml, interceptor/interceptor.go
Release branch containing…
- Add temporary debugging code to dump http headers on specific requests
Note, this release is intended to only be released to staging. Although safe to be deployed to prod there'll be a further release reverting this change to follow.
Ensure tests pass and only expected commits.
Anyone
=> Release 2.13.0

.golangci.yml, interceptor/interceptor.go
Revert temporary debugging code that was added to help with api-router refactoring
Ensure only temp code reverted and tests pass
Anyone
=> Revert temporary debugging code

.golangci.yml, interceptor/interceptor.go
Release branch containing…
- Revert temporary debugging code
Ensure only expected commits and tests pass
Anyone
=> Release 2.14.0

interceptor/interceptor.go
added otel middleware to outbound proxy transport
check that changes look sane & CI passes. Functional check to be done in sandbox
Fran
=> added otel instrumentation to proxy transport

config/config.go, config/config_test.go, service/service.go, service/service_test.go
Removed references for `dp-search-reindex-api`
- CI test pass
- Sense check
!Me
=> Removed search reindex references

middleware/beta.go, middleware/beta_test.go, proxy/proxy.go
Release 2.22.0
check release is ok
Anyone
=> use version config instead of /v1

service/service.go
- interceptor check replaced with cfg value
- Check if the changes are correct
@anyone
=> interceptor check replaced with cfg value

service/service.go
Added a log line to show what deprecations have been configured on startup.
Ensure log line makes sense and is to standard
Anyone
=> add logging for deprecation loading

service/service.go
use `enableInterceptor` feature flag for hierarchy api proxy to test rewriting
check changes are ok
Anyone
=> feature flag hierarchy api

service/service.go
using feature flag `enableInterceptor` to test observation-api rewriting
Check changes are ok
Anyone
=> set interceptor feature flag

service/service.go
- Using feature flag enableInterceptor to test code-list-api rewriting
Check changes are ok
Anyone
=> Disable interceptor

service/service.go
Set interceptor to be true 
Check changes are ok
Anyone
=> set interceptor to true

service/service.go
Feature flag for observation-api to test within sandbox
Check changes are ok
Anyone
=> feature flagged interceptor

service/service.go
Use `enableInterceptor` feature flag for dp-cantabular-filter-flex-api to test URL rewriting
Confirm changes are ok
Anyone
=> interceptor for filter flex api

service/service.go
Use `enableInterceptor` feature flag for dp-filter-api
Confirm above has been done
Anyone
=> set filter api interceptor

README.md
- Add ENABLE_INTERCEPTOR env var to the readme
- Add URL rewriting documentation 
Anyone
=> Add documentation for URL rewriting
